config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root 'home#index'
  resources :userlist
  resources :carts
  #resources :items
  #resources :sections

  get '/search' => 'categories#search'
  get '/searchresults' => 'categories#searchresults'
  get '/searchsub' => 'subcategories#search'
  get '/searchresultssub' => 'subcategories#searchresults'
  get '/searchitem' => 'items#search'
  get '/searchresultsitems' =>'items#searchresults'

  get '/add_item'  => 'items#additem'
  post'/item_save' => 'items#create'
  get '/item_save' => 'items#index'
  get '/buy' => 'carts#buy'
  get '/address' => 'carts#address'
  resources :categories do
    resources :subcategories do
      resources :items, only: [:show, :index, :edit, :destroy, :index, :update]
    end
  end
end

app/controllers/userlist_controller.rb
# this controller defines  acions for admin
class UserlistController < ApplicationController
  before_action :authenticate_user!
  before_filter :owner_only

  def index
   
    @users = User.all
  end

  def new
    @user = User.new
  end

  def show
    # @user = User.find_by_id(params[:id])
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(secure_params)
    if @user.save
      UserMailer.welcome_email(@user).deliver_now
      redirect_to userlist_index_path, :notice => "User created."
    else
      redirect_to userlist_index_path, :notice => "User not created."
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(secure_params)
      redirect_to userlist_index_path, :notice => "User updated."
    else
      redirect_to userlist_index_path, :alert => "Unable to update user."
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to userlist_index_path, :notice => "User deleted."
  end

  def owner_only
    unless current_user.owner?
      redirect_to root_path, :notice => "Access denied."

    end
  end


  private

  def secure_params
    params.require(:user).permit(:email, :password, :password_confirmation,:role,:avatar)
  end

end

app/views/userlist/_formforuser.html.erb
<h2>Sign up</h2>
<%= form_for(:user, url:  userlist_path, method: 'put') do |f| %>
<p>
    <%= f.label :Email %><br>
    <%= f.email_field :email %>
</p>
 
<p>
    <%= f.label :password %><br>
    <%=f.password_field :password %>
</p>
<p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
    <%= f.file_field :avatar %>
</p>
<p>
   	<%= f.select(:role,User.roles.keys.map{|role| [role.titleize,role]}) %>
    <%= f.submit "Save user" %>
 </p>
<%end%>



  

app/views/userlist/_formforusernew.html.erb
<h2>Sign up</h2>
<%= form_for(:user, url: userlist_index_path, method: 'post') do |f| %>
<p>
    <%= f.label :Email %><br>
    <%= f.email_field :email %>
</p>
 
<p>
    <%= f.label :password %><br>
    <%=f.password_field :password %>
</p>
<p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
    <%= f.file_field :avatar %>
</p>
<p>
   	<%= f.select(:role,User.roles.keys.map{|role| [role.titleize,role]}) %>
    <%= f.submit "Save user" %>
</p>
<%end%>



  

app/views/userlist/_user.html.erb
<%=  user.email %>

app/views/userlist/edit.html.erb
<h1>Edit user</h1>
<%= render 'formforuser' %>
<%= link_to 'Back', userlist_index_path %>

app/views/userlist/index.html.erb
 <div class = "corner" >
 <h2><%= link_to 'Create new user' ,new_userlist_path,class: "btn btn-small btn-success" %><h2><br>
 <div class="container">
 <table class="table table-striped">
    <tr>
        <th><font size="4">Email</th></font>
        <th><font size="4">Role</th></font>
        <th></th>
        <th></th>
    </tr>
    <% @users.each do |user| %>
    <tr>
        <td><%=  user.email %></td>
        <td><%=  user.role %></td>
        <td><%= link_to 'Edit', edit_userlist_path(user),class: "btn btn-small btn-success" %></td>
        <td>
        <%= link_to "Delete user", userlist_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete,class: "btn btn-small btn-success"%>
        </td>
    </tr>
    <%end%>
<table> 
<%= link_to 'categories list',categories_path,class: "btn btn-small btn-success"%>
</div>

app/views/userlist/new.html.erb
<h1><font color = "red">New User</h1></font>
<%= render 'formforusernew' %>
<div class = "corner" >
<%= link_to 'Back', userlist_index_path,class: "btn btn-small btn-success" %>
</div>