config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root 'home#index'
  resources :userlist
  resources :carts
  #resources :items
  #resources :sections

  get '/search' => 'categories#search'
  get '/searchresults' => 'categories#searchresults'
  get '/searchsub' => 'subcategories#search'
  get '/searchresultssub' => 'subcategories#searchresults'
  get '/searchitem' => 'items#search'
  get '/searchresultsitems' =>'items#searchresults'

  get '/add_item'  => 'items#additem'
  post'/item_save' => 'items#create'
  get '/item_save' => 'items#index'
  get '/buy' => 'carts#buy'
  get '/address' => 'carts#address'
  resources :categories do
    resources :subcategories do
      resources :items, only: [:show, :index, :edit, :destroy, :index, :update]
    end
  end
end

app/models/subcategory.rb
# subcategories of main categories like smartphones, laptop, text books etc.
class Subcategory < ApplicationRecord
  validates :name, presence: true,
          length: { minimum: 4 }
  belongs_to :category
  has_many:items, dependent: :destroy
end

app/controllers/subcategories_controller.rb
# this controller defines all actions upon subcategories
class SubcategoriesController < ApplicationController
  
  before_action :authenticate_user!
  before_filter :owner_only, :except => [:index, :search, :searchresults]
  def index
    @category = Category.find(params[:category_id])
    @subcategories = @category.subcategories.all
  end

  def new
    @category = Category.find(params[:category_id])
    @subcategory = @category.subcategories.new
  end

  def search
  end

  def searchresults
    @category = Category.find(params[:id])
    @results = @category.subcategories.where("name LIKE '%#{params[:word]}%' ")
  end

  def edit
    @category = Category.find(params[:category_id])
    @subcategory = @category.subcategories.find(params[:id])
  end

  def create
    @category = Category.find(params[:category_id])
    @subcategory = @category.subcategories.create(sub_params)
    if @subcategory.save
      redirect_to category_subcategories_path, :notice => "subcategory created."
    else
      redirect_to category_subcategories_path, :notice => "subcategory not created."
    end
  end

  def update
    @category = Category.find(params[:category_id])
    @subcategory = @category.subcategories.find(params[:id])
    if @subcategory.update(sub_params)
      redirect_to category_subcategories_path, :notice => "subcategory updated."
    else
      redirect_to category_subcategories_path, :alert => "Unable to update subcategory"
    end
  end

  def destroy
    @category = Category.find(params[:category_id])
    @subcategory = @category.subcategories.find(params[:id])
    @subcategory.destroy
    redirect_to category_subcategories_path, :notice => "subcategory deleted."
  end

  def owner_only
    unless current_user.owner?
      redirect_to root_path, :notice => "Access denied."
    end
  end

  private

  def sub_params
    params.require(:subcategory).permit(:name)
  end

end

app/views/subcategories/edit.html.erb
<h2> Edit </h2> 
<%= form_for @subcategory, :url => { :action => "update" } do |f| %>
<p>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.submit "save subcategory" %>
  </p>
<% end %>
 

app/views/subcategories/index.html.erb
<div class = "corner">
<% if current_user.role == "owner" %>
<%= link_to "add subcategories",new_category_subcategory_path ,class: "btn btn-small btn-success"%><br><br>
<% end %>
<%#= @category.id %>
<%= link_to 'search subcategory', searchsub_path(category_id:@category.id),class: "btn btn-small btn-success"%><br><br>
<% if @category.subcategories.all.empty? %>
<h3> No Subcategories </h3>
<% else %>
<table>
	<tr>
		<th><u><font size="5">Subcategories</u></font></th>
	</tr>
    <% @subcategories.each do |subcategory| %>
    <tr>
          <td>   
	      <%=  link_to subcategory.name, category_subcategory_items_path(@category,subcategory) %>
          </td>
          <td>
           <% if current_user.role == "owner" %>
           <%= link_to "Delete ", category_subcategory_path(@category,subcategory), :data => { :confirm => "Are you sure?" }, :method => :delete,class: "btn btn-small btn-success" %>
          </td>
          <td>
           <%= link_to "Edit ", edit_category_subcategory_path(@category,subcategory),class: "btn btn-small btn-success" %>
           <% end %>
          </td>
    </tr>
    <%end%>
<table>   
<% end %>    
</div>
 

app/views/subcategories/new.html.erb
<h2> New </h2>
<%= form_for @subcategory, :url => { :action => "create" } do |f| %>
<p>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.submit "save subcategory" %>
  </p>
<% end %>
 

  

app/views/subcategories/search.html.erb
<%#= params[:category_id] %>
<%#console%>
<%#= form_tag( "/searchresultssub", method: "get") do %>
<%= form_tag( { :controller => "subcategories", :action => "searchresults" }, { :method => "get" })do %>
  <%= label_tag(:word, "Search for subcategory:") %>
  <%= text_field_tag(:word,) %>
  <%= hidden_field_tag 'id', params[:category_id]  %>
  <%= submit_tag("Search") %>
<% end %>




<%#= form_for :subcategory, :url => {:controller => "subcategories", :action => "searchresults" }, method:"get" do |f| %>
<p>
<%#= f.label :search %>
<%#= f.text_field :word %>
</p>

</p>
 
    <%#= f.submit "Search" %>
</p>

<%# end %>

app/views/subcategories/searchresults.html.erb
<h3>Search results for subcategory</h3>
<%if @results.empty? %>
<h3> No results found</h3>
<% else %>
<% @results.each do |result| %>
<%= link_to result.name,category_subcategory_items_path(@category,result)  %><br>
<% end %>
<% end %>