config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root 'home#index'
  resources :userlist
  resources :carts
  #resources :items
  #resources :sections

  get '/search' => 'categories#search'
  get '/searchresults' => 'categories#searchresults'
  get '/searchsub' => 'subcategories#search'
  get '/searchresultssub' => 'subcategories#searchresults'
  get '/searchitem' => 'items#search'
  get '/searchresultsitems' =>'items#searchresults'

  get '/add_item'  => 'items#additem'
  post'/item_save' => 'items#create'
  get '/item_save' => 'items#index'
  get '/buy' => 'carts#buy'
  get '/address' => 'carts#address'
  resources :categories do
    resources :subcategories do
      resources :items, only: [:show, :index, :edit, :destroy, :index, :update]
    end
  end
end

app/models/item.rb
# for each individual items inside the subcategiries.
class Item < ApplicationRecord
  validates :name, presence: true,
             length: { minimum: 4 }
  validates :description, presence: true,
             length: { minimum: 4 }
  validates :price, presence: true,
            format: { :with => /\A(\$)?(\d+)(\.|,)?\d{0,2}?\z/  }     
  has_attached_file :image,styles:{ medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  belongs_to :subcategory
  
end

app/controllers/items_controller.rb
# it defines all actions on items
class ItemsController < ApplicationController
  before_action :authenticate_user!
  before_filter :vendor_only, :only => [:new, :edit, :create, :update,:destroy,:additem]
  def index
    @subcategory = Subcategory.find(params[:subcategory_id])
    @items = @subcategory.items.all
  end

  def new
    @category = Category.find(params[:category_id])
    @subcategory = @category.subcategories.find(params[:subcategory_id])
    @item = @subcategory.items.new
  end

  def show
    @category = Category.find(params[:category_id])
    @subcategory = @category.subcategories.find(params[:subcategory_id])
    # @subcategory = Subcategory.find(params[:subcategory_id])
    @item = @subcategory.items.find(params[:id])
    # @item = Items.find(params[:id])
  end

  def search
  end

  def searchresults
    @category = Category.find(params[:cat_id])
    @subcategory = @category.subcategories.find(params[:sub_id])
    @results = @subcategory.items.where("name LIKE '%#{params[:word]}%' ")
  end


  def edit
    @category = Category.find(params[:category_id])
    @subcategory = @category.subcategories.find(params[:subcategory_id])
    @item = @subcategory.items.find(params[:id])
  end

  def create
    @subcategory = Subcategory.find(params[:subcategory_id])
    # @subcategory = Subcategory.find(params[:item][:subcategory_id])
    @item = @subcategory.items.create(item_params)

    if @item.save
      # redirect_to  category_subcategory_items_path(:subcategory_id => params[:subcategory_id]), :notice => "Item created."
      # render text: 'Saved'
      redirect_to  root_path, :notice => "Item created."

    else
      # redirect_to  category_subcategory_items_path, :notice => "Item not created."
      # render text: ' Not Saved'
       redirect_to  root_path, :notice => "Item not created."
    end
  end

  def update
    @category = Category.find(params[:category_id])
    @subcategory = @category.subcategories.find(params[:subcategory_id])
    @item = @subcategory.items.find(params[:id])
    if @item.update(item_params)
        redirect_to  category_subcategory_items_path, :notice => "Item created."
    else
      redirect_to  category_subcategory_items_path, :notice => "Item not created."
    end
  end

  def destroy
    @category = Category.find(params[:category_id])
    @subcategory = @category.subcategories.find(params[:subcategory_id])
    @item = @subcategory.items.find(params[:id])
    @item.destroy
    redirect_to category_subcategory_items_path, :notice => "deleted"
  end

  def additem
  end

  def vendor_only
    unless current_user.vendor?
      redirect_to root_path, :notice => "Access denied."
    end
  end

  private

  def item_params
    params.require(:item).permit(:name,:description, :price, :image,:userid,:enddate,:stock,:count)
  end

end

app/helpers/item_helper.rb
module ItemHelper
end

app/views/items/additem.html.erb
<div class = "corner">
<h2> Add an Item </h2>
<%= form_for(:item, url: item_save_path) do |f| %>
  <p>
    <%#= select_tag "category_id", options_from_collection_for_select(Category.all, "id", "name") %><br>
    <%= select_tag "subcategory_id", options_from_collection_for_select( Subcategory.all, "id", "name") %><br><br>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </p>
 <%= f.hidden_field :userid, :value => current_user.id%>
 <%= f.hidden_field :count, :value => 0 %>
  <p>
    <%= f.label :'upload item image' %><br>
    <%=f.file_field :image %><br>
  </p>
  <p>
    <%= f.label :'End date' %><br>
    <%=f.datetime_local_field :enddate, include_seconds: true %>
  </p><br> 
  <p>
    <%= f.label :'Stock' %><br>
    <%=f.number_field :stock%>
  </p><br>
  <p>
    <%= f.submit "save" %>
  </p>
<% end %>
</div>

app/views/items/edit.html.erb
<div class = "corner">
<h2> Add an item </h2>
<%= form_for @item, :url => { :action => "update" } do |f| %>
<p>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </p>
  <p>
    <%= f.label :'upload item image' %><br>
    <%=f.file_field :image %><br>
  </p>
  <p>
     <%= f.label :'End date' %><br>
     <%=f.datetime_local_field :enddate, include_seconds: true %>
  </p>
  <p>
    <%= f.label :'Stock' %><br>
    <%=f.number_field :stock %>
  </p><br>
  <br>
  <p>
    <%= f.submit "save" %>
  </p>
<% end %>
</div>

app/views/items/index.html.erb
<!-- < for countdwon timer > -->
<script>
function count(id,date){

var d = new Date();
var ed = new Date(date);
var dateText = document.getElementById(id);
var seconds = Math.floor((ed - (d))/1000) - 19800;

if(seconds<=0){
    d="No offer";
    dateText.innerHTML = d;
    return;
}
var minutes = Math.floor(seconds/60);
var hours = Math.floor(minutes/60);
var days = Math.floor(hours/24);

hours = hours-(days*24);
minutes = minutes-(days*24*60)-(hours*60);
seconds = seconds-(days*24*60*60)-(hours*60*60)-(minutes*60);
dateText.innerHTML = d;
var t;
function down() {
    seconds--;
    if (seconds < 0) {
        seconds = 60;
        minutes--;
        if (minutes < 0) 
        {
            minutes = 60;
            hours--;
            if (hours < 0)
            {
                hours = 24;
                days--;
                if (days < 1)
                {
                    days =30;
                    month--;
                    if(month < 1)
                    {
                        month = 12;
                        year--;
                    }
                }
            }    
        }
    }
    
d ="offer ends in " + days +"days" + "\r\n"+(hours ? (hours > 9 ? hours : "0" + hours) : "00") + ":" + (minutes ? (minutes > 9 ? minutes : "0" + minutes) : "00") + ":" + (seconds > 9 ? seconds : "0" + seconds);
dateText.innerHTML = d;
timer();
}
function timer() {
t = setTimeout(down, 1000);
}
timer();
}
</script>

<div class = "corner">
<% if current_user.role == "vendor" %>
<%= link_to "Add item ",add_item_path(),class: "btn btn-small btn-success" %><br><br>
<% end %>
<%= link_to "Search item",searchitem_path(subcategory_id: @subcategory.id,category_id: params[:category_id] ),class: "btn btn-small btn-success" %><br><br><br><br>
<% if @subcategory.items.empty? %>
<h3> No Items found </h3>
<% else %>
<div class="container">
<table class="table table-striped">
<thead>
    <tr>
        <th><font size="4">Name</th></font>
        <th><font size="4">Price(in Rupees)</th></font>
        <th><font size="4">Description</th></font>
        <th></th>
        <th></th>
    </tr>
</thead>
    <% @items.each do |item| %>
<tbody>
    <tr>
        <td><%= link_to item.name,  category_subcategory_item_path(:id => item.id )%><p id=<%= item.id %> style =  "color:red" ></p></td>
        <td><%= item.price %></td>
        <td><%= item.description %></td>
        <td><%= image_tag item.image.url(:thumb)%></td>
        <% if current_user.role == "customer" %>
        <td><%= link_to 'Add to cart', carts_path( :controller => 'carts', :action => 'create', :id => item.id, subcategory_id: @subcategory.id,category_id: params[:category_id]), method: :post,class: "btn btn-small btn-success" %>
            <%#= number_field_tag 'quantity', 1, within: 1...10 %>
        <% end %>    
        <% if current_user.role == "vendor" %>
        <% if item.userid == current_user.id %>
        <td><%= link_to 'Edit' ,edit_category_subcategory_item_path(:id => item.id ),class: "btn btn-small btn-success"%></td>
        <td><%= link_to 'Delete' ,category_subcategory_item_path(:id => item.id ), :data => { :confirm => "Are you sure?" }, :method => :delete  ,class: "btn btn-small btn-success"  %></td>
        <% end %>
        <% end %>
        <script > count(<%= item.id %>,'<%= item.enddate %>');</script>
        <% if current_user.role == "customer" %>
        <% if (item.stock - item.count) > 0 %>
        <br><font color = "red"><%="#{item.stock - item.count}" + "remainig"%></font>
        <% else %><br>
        <font color = "red"><%= "Out of stock" %></font>
        <% end %>
        <% end %>
    </tr>
</tbody>
    <%end%>
<table>   
</div>    
<% end %>
</div>

app/views/items/new.html.erb
<div class = "corner">
<h2> Add an item </h2>
<%= form_for :item, :url => { :action => "create" } do |f| %>
<p>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </p>
  <p>
    <%= f.label :'upload item image' %><br>
    <%=f.file_field :image %><br>
  </p>
  <p>
    <%= f.label :'upload item image' %><br><br>
    <%=f.datetime_local_field :enddate, include_seconds: true %>
  </p>
  <br>
  <p>
    <%= f.label :'Stock' %><br>
    <%=f.number_field :stock%>
  </p><br>
  <p>
  <%= f.submit "save" %>
  </p>
<% end %>
</div>
 

app/views/items/search.html.erb
<%= form_tag( { :controller => 'items', :action => 'searchresults' }, {:method => "get" }) do %>
  <%= label_tag(:word, "Search for items:") %>
  <%= text_field_tag(:word,) %>
  <%= hidden_field_tag 'sub_id', params[:subcategory_id]  %>
  <%= hidden_field_tag 'cat_id', params[:category_id]  %>
  <%= submit_tag("Search") %>
<% end %> 

app/views/items/searchresults.html.erb
<div class = "corner">
<h3> Search Results </h3>
<%if @results.empty? %>
<h3> No Results Found</h3>
<% else %>
<% @results.each do |result| %>
<%= link_to result.name, category_subcategory_item_path(category_id: params[:cat_id], subcategory_id: params[:sub_id], :id => result.id ) %><br>
<% end %>
<% end %>
</div>

app/views/items/show.html.erb
<div class = "corner" >
<font size = '5' ><%= @item.name %></font><br><br>
<font color = 'red'><%= "#{@item.price}"+"$" %></font><br><br>
<%= @item.description %><br><br>
<%= image_tag @item.image.url(:medium) %><br><br>
<% if current_user.role == "customer" %>
<%= link_to 'Add to cart', carts_path( :controller => 'carts', :action => 'create', :id => params[:id], subcategory_id: params[:subcategory_id],category_id: params[:category_id]), method: :post ,class: "btn btn-small btn-success"%>
<% end %>
</div>