config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root 'home#index'
  resources :userlist
  resources :carts
  #resources :items
  #resources :sections

  get '/search' => 'categories#search'
  get '/searchresults' => 'categories#searchresults'
  get '/searchsub' => 'subcategories#search'
  get '/searchresultssub' => 'subcategories#searchresults'
  get '/searchitem' => 'items#search'
  get '/searchresultsitems' =>'items#searchresults'

  get '/add_item'  => 'items#additem'
  post'/item_save' => 'items#create'
  get '/item_save' => 'items#index'
  get '/buy' => 'carts#buy'
  get '/address' => 'carts#address'
  resources :categories do
    resources :subcategories do
      resources :items, only: [:show, :index, :edit, :destroy, :index, :update]
    end
  end
end

app/models/category.rb
# for categories like mobiles, computers, books etc.
class Category < ApplicationRecord
  validates :name, presence: true,
          length: { minimum: 4 }
  has_many:subcategories, dependent: :destroy
end

app/controllers/categories_controller.rb
# this controller defines all actions on categories.
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_filter :owner_only, :except => [:index, :search, :searchresults]
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def show
    @category = Category.find(params[:id])
  end

  def edit
    @category = Category.find(params[:id])
  end

  def search
  end

  def searchresults
    @results = Category.where("name LIKE '%#{params[:word]}%' ")
  end

  def create
    @category = Category.new(secure_params)
    if @category.save
      redirect_to categories_path, :notice => "category created"
    else
      redirect_to categories_path, :notice => "category not created."
    end
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(secure_params)
      redirect_to categories_path, :notice => "category updated."
    else
      redirect_to categories_path, :alert => "Unable to update category"
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_path, :notice => "category deleted."
  end

  def owner_only
    unless current_user.owner?
      redirect_to root_path, :notice => "Access denied."
    end
  end

  private

  def secure_params
    params.require(:category).permit(:name)
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/edit.html.erb
<h2>Edit category</h2>
<%= form_for(:category, url: category_path, method: 'put') do |f| %>
<p>
    <%= f.label :Name %><br>
    <%= f.text_field :name %>
</p>
 
    <%= f.submit "Save Category" %>
</p>
<%end%>



  

app/views/categories/index.html.erb
<div class = "corner" >
<% if user_signed_in? %>
<% if current_user.role =='owner' %>
<%= link_to 'Users list', {:controller => :userlist, :action => :index},class: "btn btn-small btn-success" %><br><br><br>
<%end%>
<%end%>
<% if current_user.role == "owner" %>
<%= link_to 'Add Category',new_category_path,class: "btn btn-small btn-success" %><br> <br>
<% end %>
<% if user_signed_in? %>
<% if current_user.role =='vendor' %>
<%= link_to 'Add products',add_item_path,class: "btn btn-small btn-success" %><br><br>
<%end%>
<%end%>
<%= link_to 'Search Category',search_path,class: "btn btn-small btn-success"%><br><br>
<table>
	<tr>
    <th><u><font size="5">Categories</th></font></u>
    </tr>
    <% @categories.each do |category| %>
    <tr>
        <td><%= link_to category.name,  category_subcategories_path(category)%></td>
        <% if current_user.role == "owner" %>
        <td><%= link_to 'Edit', edit_category_path(category),class: "btn btn-small btn-success" %></td>
        <td>
        <%= link_to "Delete ", category_path(category), :data => { :confirm => "Are you sure?" }, :method => :delete,class: "btn btn-small btn-success"%>
        </td>
        <% end %>
    </tr>
    <%end%>
<table>
</div>

app/views/categories/new.html.erb
<h2>Add Category</h2>
<%= form_for(:category, url: categories_path, method: 'post') do |f| %>
<p>
    <%= f.label :Name %><br>
    <%= f.text_field :name %>
</p>
 
    <%= f.submit "Save category" %>
</p>
<%end%>



  

app/views/categories/search.html.erb
<%= form_tag("/searchresults", method: "get") do %>
  <%= label_tag(:word, "Search for:") %>
  <%= text_field_tag(:word) %>
  <%= submit_tag("Search") %>
<% end %>

app/views/categories/searchresults.html.erb
<h3>Search Results</h3>
<% if @results.empty? %>
<h3> No results found </h3>
<% else %>
<% @results.each do |result| %>
<%= link_to result.name, category_subcategories_path(result) %><br>
<% end %>
<% end %>